### ISSUE TITLE
Fey are able to despawn

### ISSUE THREAD

**Issue by LemmaEOF** [Modfest-1-15-Team-Cornflower/Cornflower#6]
Fey aren't flagged as unable to despawn, meaning that if you move too far away from your automation setup, you'll lose all of them and have to recraft them all.

**Comment by chrissquest** [comment]
Returned canImmediatelyDespawn to false in [96c1ec9](https://github.com/Modfest-1-15-Team-Cornflower/Cornflower/commit/96c1ec9d80068025c16e2600daa1fac8f8823c98)
